# Generated by Django 4.2.10 on 2024-02-25 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50, verbose_name="用户名")),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "real_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="用户真实姓名",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="性别"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=50, verbose_name="邮箱"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="电话"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="移动电话"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.IntegerField(blank=True, null=True, verbose_name="更新人"),
                ),
                ("remove", models.BooleanField(default=False, verbose_name="删除标志")),
                (
                    "data_filter",
                    models.TextField(
                        blank=True, default="", max_length=200, verbose_name="数据过滤"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, default="", max_length=45, verbose_name="主题"
                    ),
                ),
                (
                    "default_page",
                    models.CharField(
                        blank=True, default="", max_length=45, verbose_name="缺省页面"
                    ),
                ),
                (
                    "logo_image",
                    models.CharField(
                        blank=True, default="", max_length=45, verbose_name="Logo"
                    ),
                ),
                (
                    "qq_openid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="用于第三方登录的凭证",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        default="1.0",
                        max_length=10,
                        verbose_name="检测app的版本号",
                    ),
                ),
                (
                    "json_auth",
                    models.TextField(
                        blank=True,
                        default="{}",
                        max_length=1000,
                        verbose_name="用于app的权限控制（json串里有权限点的配置）",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统管理员",
                "verbose_name_plural": "系统管理员",
                "db_table": "system_administrator",
            },
        ),
        migrations.CreateModel(
            name="DayNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="日期"
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="网站访问次数")),
            ],
            options={
                "verbose_name": "网站日访问量统计",
                "verbose_name_plural": "网站日访问量统计",
            },
        ),
        migrations.CreateModel(
            name="Elder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="老人姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=5,
                        verbose_name="性别",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "checkin_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="入养老院日期"
                    ),
                ),
                (
                    "checkout_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="离开养老院日期"
                    ),
                ),
                (
                    "imgset_dir",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="图像目录"
                    ),
                ),
                (
                    "profile_photo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="头像路径"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="房间号"
                    ),
                ),
                (
                    "firstguardian_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第一监护人姓名",
                    ),
                ),
                (
                    "firstguardian_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="与第一监护人关系",
                    ),
                ),
                (
                    "firstguardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第一监护人电话",
                    ),
                ),
                (
                    "firstguardian_wechat",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第一监护人微信",
                    ),
                ),
                (
                    "secondguardian_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第二监护人姓名",
                    ),
                ),
                (
                    "secondguardian_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="与第二监护人关系",
                    ),
                ),
                (
                    "secondguardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第二监护人电话",
                    ),
                ),
                (
                    "secondguardian_wechat",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第二监护人微信",
                    ),
                ),
                (
                    "health_state",
                    models.CharField(
                        blank=True,
                        default="良好",
                        max_length=50,
                        null=True,
                        verbose_name="健康状况",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.IntegerField(blank=True, null=True, verbose_name="更新人"),
                ),
                ("remove", models.BooleanField(default=False, verbose_name="删除标志")),
            ],
            options={
                "verbose_name": "老人信息",
                "verbose_name_plural": "老人信息",
                "db_table": "elder_info",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.IntegerField(
                        choices=[
                            (0, "情感检测"),
                            (1, "义工交互检测"),
                            (2, "陌生人检测"),
                            (3, "摔倒检测"),
                            (4, "禁止区域入侵检测"),
                        ],
                        default=0,
                        verbose_name="事件id",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="事件发生时间")),
                (
                    "event_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="事件发生地点",
                    ),
                ),
                (
                    "event_desc",
                    models.TextField(
                        blank=True, default="", max_length=200, verbose_name="事件描述"
                    ),
                ),
                (
                    "oldperson_id",
                    models.IntegerField(blank=True, null=True, verbose_name="老人id"),
                ),
            ],
            options={
                "verbose_name": "事件记录",
                "verbose_name_plural": "事件记录",
                "db_table": "event_record",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="工作人员姓名"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=5,
                        verbose_name="性别",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="电话"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="身份证号"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入职日期"),
                ),
                (
                    "resign_date",
                    models.DateField(blank=True, null=True, verbose_name="离职日期"),
                ),
                (
                    "imgset_dir",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="图像目录"
                    ),
                ),
                (
                    "profile_photo",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="头像路径"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.IntegerField(blank=True, null=True, verbose_name="更新人"),
                ),
                ("remove", models.BooleanField(default=False, verbose_name="删除标志")),
            ],
            options={
                "verbose_name": "工作人员",
                "verbose_name_plural": "工作人员",
                "db_table": "staff_info",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="用户名")),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        unique=True,
                        verbose_name="电话",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=30, verbose_name="IP 地址")),
                (
                    "ip_addr",
                    models.CharField(max_length=30, verbose_name="IP 地理位置"),
                ),
                (
                    "end_point",
                    models.CharField(
                        default="/", max_length=30, verbose_name="访问端点"
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="访问次数")),
            ],
            options={
                "verbose_name": "访问用户信息",
                "verbose_name_plural": "访问用户信息",
            },
        ),
        migrations.CreateModel(
            name="VisitNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=0, verbose_name="网站访问总次数"),
                ),
            ],
            options={
                "verbose_name": "网站访问总次数",
                "verbose_name_plural": "网站访问总次数",
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="义工姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=5,
                        verbose_name="性别",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="电话"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="身份证号"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "checkin_date",
                    models.DateField(blank=True, null=True, verbose_name="访问日期"),
                ),
                (
                    "checkout_date",
                    models.DateField(blank=True, null=True, verbose_name="离开日期"),
                ),
                (
                    "imgset_dir",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="图像目录"
                    ),
                ),
                (
                    "profile_photo",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="头像路径"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.IntegerField(blank=True, null=True, verbose_name="更新人"),
                ),
                ("remove", models.BooleanField(default=False, verbose_name="删除标志")),
            ],
            options={
                "verbose_name": "义工",
                "verbose_name_plural": "义工",
                "db_table": "volunteer_info",
            },
        ),
    ]
