# Generated by Django 4.2.10 on 2024-05-14 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="日期"
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="网站访问次数")),
            ],
            options={
                "verbose_name": "网站日访问量统计",
                "verbose_name_plural": "网站日访问量统计",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.IntegerField(
                        choices=[
                            (0, "情感纠纷"),
                            (1, "意外事件"),
                            (2, "特殊事件"),
                            (3, "服务求助"),
                            (4, "日常协助"),
                        ],
                        default=0,
                        verbose_name="事件类型",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="事件发生时间")),
                (
                    "event_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="事件发生地点",
                    ),
                ),
                (
                    "event_desc",
                    models.TextField(
                        blank=True, default="", max_length=200, verbose_name="事件描述"
                    ),
                ),
                (
                    "oldperson_id",
                    models.IntegerField(blank=True, null=True, verbose_name="老人id"),
                ),
                (
                    "op_id",
                    models.IntegerField(blank=True, null=True, verbose_name="记录者id"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
            ],
            options={
                "verbose_name": "事件记录",
                "verbose_name_plural": "事件记录",
                "db_table": "event_record",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="服务名称"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="服务内容"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="服务描述"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily_care", "日常护理"),
                            ("medical_care", "医疗护理"),
                            ("rehabilitation", "康复护理"),
                            ("leisure", "休闲活动"),
                            ("education", "教育活动"),
                            ("mental_health", "精神健康"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="服务类型",
                    ),
                ),
                (
                    "target_group",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="服务对象"
                    ),
                ),
                (
                    "service_hours",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="服务时间"
                    ),
                ),
                (
                    "service_area",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="服务区域"
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, null=True, verbose_name="服务人员资质"
                    ),
                ),
                (
                    "customer_reviews",
                    models.TextField(blank=True, null=True, verbose_name="客户评价"),
                ),
                (
                    "additional_costs",
                    models.TextField(blank=True, null=True, verbose_name="附加费用"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="服务费用",
                    ),
                ),
                (
                    "service_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_photo/"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="下单次数"
                    ),
                ),
            ],
            options={
                "verbose_name": "服务",
                "verbose_name_plural": "服务",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        default="匿名用户", max_length=50, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="移动电话"
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("0", "管理员"),
                            ("1", "工作人员"),
                            ("2", "老年用户"),
                            ("3", "义工用户"),
                            ("4", "其他"),
                        ],
                        default="3",
                        max_length=1,
                        verbose_name="类别",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="自我介绍"),
                ),
                (
                    "user_photo",
                    models.ImageField(blank=True, null=True, upload_to="user_photo/"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.CreateModel(
            name="VisitNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=0, verbose_name="网站访问总次数"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="计数类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "网站访问总次数",
                "verbose_name_plural": "网站访问总次数",
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="义工姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=5,
                        verbose_name="性别",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="移动电话"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="座机电话"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入职日期"),
                ),
                (
                    "resign_date",
                    models.DateField(blank=True, null=True, verbose_name="离职日期"),
                ),
                (
                    "volunteer_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="volunteer_photo/"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "bind_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volunteer_data",
                        to="app.user",
                        verbose_name="绑定用户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to="app.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_updated",
                        to="app.user",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "义工",
                "verbose_name_plural": "义工",
                "db_table": "volunteer_info",
            },
        ),
        migrations.CreateModel(
            name="UserIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "ip_addr",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="IP 地理位置"
                    ),
                ),
                (
                    "end_point",
                    models.CharField(
                        blank=True,
                        default="/",
                        max_length=30,
                        null=True,
                        verbose_name="访问端点",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="访问次数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="登录时间"
                    ),
                ),
                (
                    "user_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_user_by",
                        to="app.user",
                        verbose_name="账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "访问用户信息",
                "verbose_name_plural": "访问用户信息",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="工作人员姓名"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=5,
                        verbose_name="性别",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="移动电话"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="座机电话"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入职日期"),
                ),
                (
                    "resign_date",
                    models.DateField(blank=True, null=True, verbose_name="离职日期"),
                ),
                (
                    "staff_photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photo/"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "bind_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_data",
                        to="app.user",
                        verbose_name="绑定用户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to="app.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_updated",
                        to="app.user",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作人员",
                "verbose_name_plural": "工作人员",
                "db_table": "staff_info",
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_name",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="工作人员"
                    ),
                ),
                (
                    "staff_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="工作人员联系方式",
                    ),
                ),
                (
                    "volunteer_name",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="义工"
                    ),
                ),
                (
                    "volunteer_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="义工联系方式",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作区域"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "星期一"),
                            (2, "星期二"),
                            (3, "星期三"),
                            (4, "星期四"),
                            (5, "星期五"),
                            (6, "星期六"),
                            (7, "星期天"),
                        ],
                        null=True,
                        verbose_name="星期",
                    ),
                ),
                (
                    "shift",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "时间段 1: 08:00-10:20"),
                            (2, "时间段 2: 10:20-12:40"),
                            (3, "时间段 3: 12:40-15:00"),
                            (4, "时间段 4: 15:00-17:20"),
                            (5, "时间段 5: 17:20-19:40"),
                            (6, "时间段 6: 19:40-22:00"),
                        ],
                        null=True,
                        verbose_name="班次",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_ShiftAssignment_created",
                        to="app.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_ShiftAssignment_updated",
                        to="app.user",
                        verbose_name="更新人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customerName",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="客户姓名"
                    ),
                ),
                (
                    "customerContact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "aceeptName",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="服务接受者"
                    ),
                ),
                (
                    "aceeptContact",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="服务接受者联系方式",
                    ),
                ),
                (
                    "date_scheduled",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="预定日期"
                    ),
                ),
                (
                    "date_accepted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接受日期"
                    ),
                ),
                (
                    "date_started",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始日期"
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接单"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1星"),
                            (2, "2星"),
                            (3, "3星"),
                            (4, "4星"),
                            (5, "5星"),
                        ],
                        null=True,
                        verbose_name="评分",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="反馈"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_ServiceOrder_created",
                        to="app.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="app.service",
                        verbose_name="服务",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_ServiceOrder_updated",
                        to="app.user",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务订单",
                "verbose_name_plural": "服务订单",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_Service_created",
                to="app.user",
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_Service_updated",
                to="app.user",
                verbose_name="更新人",
            ),
        ),
        migrations.CreateModel(
            name="Logging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "operation_content",
                    models.TextField(blank=True, null=True, verbose_name="操作信息"),
                ),
                (
                    "operation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADD_RESIDENT", "添加居民"),
                            ("UPDATE_RESIDENT", "更新居民信息"),
                            ("DELETE_RESIDENT", "删除居民"),
                            ("ADD_STAFF", "添加员工"),
                            ("UPDATE_STAFF", "更新员工信息"),
                            ("DELETE_STAFF", "删除员工"),
                            ("ADD_SCHEDULE", "添加排班"),
                            ("UPDATE_SCHEDULE", "更新排班信息"),
                            ("DELETE_SCHEDULE", "删除排班"),
                            ("ADD_MEDICATION", "添加用药记录"),
                            ("UPDATE_MEDICATION", "更新用药记录"),
                            ("DELETE_MEDICATION", "删除用药记录"),
                            ("ADD_ACTIVITY", "添加活动"),
                            ("UPDATE_ACTIVITY", "更新活动信息"),
                            ("DELETE_ACTIVITY", "删除活动"),
                            ("ADD_ANNOUNCEMENT", "发布公告"),
                            ("UPDATE_ANNOUNCEMENT", "更新公告"),
                            ("DELETE_ANNOUNCEMENT", "删除公告"),
                            ("ADD_FEEDBACK", "收集反馈"),
                            ("UPDATE_FEEDBACK", "处理反馈"),
                            ("DELETE_FEEDBACK", "删除反馈"),
                            ("ADD_HEALTH_RECORD", "添加健康记录"),
                            ("UPDATE_HEALTH_RECORD", "更新健康记录"),
                            ("DELETE_HEALTH_RECORD", "删除健康记录"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Logging",
                        to="app.user",
                        verbose_name="日志",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Elder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="老人姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="U",
                        max_length=5,
                        verbose_name="性别",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="移动电话"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="座机电话"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "checkin_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="入养老院日期"
                    ),
                ),
                (
                    "checkout_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="离开养老院日期"
                    ),
                ),
                (
                    "elder_photo",
                    models.ImageField(blank=True, null=True, upload_to="elder_photo/"),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="房间号"
                    ),
                ),
                (
                    "firstguardian_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第一监护人姓名",
                    ),
                ),
                (
                    "firstguardian_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="与第一监护人关系",
                    ),
                ),
                (
                    "firstguardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第一监护人电话",
                    ),
                ),
                (
                    "firstguardian_wechat",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第一监护人微信",
                    ),
                ),
                (
                    "secondguardian_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第二监护人姓名",
                    ),
                ),
                (
                    "secondguardian_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="与第二监护人关系",
                    ),
                ),
                (
                    "secondguardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第二监护人电话",
                    ),
                ),
                (
                    "secondguardian_wechat",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="第二监护人微信",
                    ),
                ),
                (
                    "health_state",
                    models.CharField(
                        blank=True,
                        default="良好",
                        max_length=50,
                        null=True,
                        verbose_name="健康状况",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "bind_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elder_data",
                        to="app.user",
                        verbose_name="绑定用户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to="app.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_updated",
                        to="app.user",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "老人信息",
                "verbose_name_plural": "老人信息",
                "db_table": "elder_info",
            },
        ),
        migrations.CreateModel(
            name="CommunityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="活动名称")),
                (
                    "introduction",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="简介"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地点"
                    ),
                ),
                (
                    "organizer",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="主办方"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="发布者"
                    ),
                ),
                (
                    "participant_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="参与人数限制"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("ongoing", "进行中"),
                            ("finished", "已结束"),
                        ],
                        default="not_started",
                        max_length=50,
                        verbose_name="活动状态",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="联系信息"
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="费用"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="communityevents/",
                        verbose_name="图片/海报",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "registration_link",
                    models.URLField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="注册/报名链接",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创键时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_save",
                    models.BooleanField(default=True, verbose_name="是否保存为草稿"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to="app.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_updated",
                        to="app.user",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区活动",
                "verbose_name_plural": "社区活动",
            },
        ),
        migrations.CreateModel(
            name="CommunityAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "introduction",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="简介"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布日期"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期日期"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="发布者"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="发布方"
                    ),
                ),
                (
                    "announcement_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="announcement_photo/"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "is_save",
                    models.BooleanField(default=True, verbose_name="是否保存为草稿"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创键时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("inactive", "暂时无效"),
                            ("expired", "过期"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to="app.user",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_updated",
                        to="app.user",
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区公告",
                "verbose_name_plural": "社区公告",
            },
        ),
    ]
