# Generated by Django 4.2.10 on 2024-02-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="user_name",
            new_name="name",
        ),
    ]
