# Generated by Django 4.2.10 on 2024-02-25 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.RenameField(
            model_name="test",
            old_name="id",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="name",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="test",
            name="phone",
        ),
        migrations.AddField(
            model_name="test",
            name="creation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 25, 9, 11, 52, 387438, tzinfo=datetime.timezone.utc
                ),
                verbose_name="创建时间",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="gender",
            field=models.CharField(
                choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                default="O",
                max_length=1,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="mobile_phone",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="电话"
            ),
        ),
    ]
