# Generated by Django 4.2.10 on 2024-02-25 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_test_options_rename_id_test_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="creation_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
    ]
