# Generated by Django 4.2.10 on 2024-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_test_creation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="电话"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="username",
            field=models.CharField(
                default="匿名用户", max_length=50, verbose_name="用户名"
            ),
        ),
    ]
