# Generated by Django 4.2.10 on 2024-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_test_phone_alter_test_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="邮箱"
            ),
        ),
    ]
