# Generated by Django 4.2.10 on 2024-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_test_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="grade",
            field=models.IntegerField(
                choices=[
                    ("0", "管理员"),
                    ("1", "工作人员"),
                    ("2", "老年用户"),
                    ("3", "子女用户"),
                    ("4", "义工用户"),
                    ("5", "其他"),
                ],
                default="5",
                max_length=1,
                verbose_name="类别",
            ),
        ),
    ]
