# Generated by Django 4.2.10 on 2024-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_test_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="自我介绍"),
        ),
    ]
