# Generated by Django 4.2.10 on 2024-02-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elder',
            name='imgset_dir',
        ),
        migrations.RemoveField(
            model_name='elder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='elder',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='elder',
            name='remove',
        ),
        migrations.AddField(
            model_name='elder',
            name='avatar_phone',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_photo/'),
        ),
    ]
