# Generated by Django 4.2.10 on 2024-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_elder_imgset_dir_remove_elder_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elder',
            old_name='avatar_phone',
            new_name='avatar_photo',
        ),
        migrations.AlterField(
            model_name='elder',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='电话'),
            preserve_default=False,
        ),
    ]
