# Generated by Django 4.2.10 on 2024-02-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_avatar_phone_elder_avatar_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='mobile',
            new_name='mobile_phone',
        ),
        migrations.AddField(
            model_name='elder',
            name='mobile_phone',
            field=models.CharField(default=12213, max_length=50, verbose_name='移动电话'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elder',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='test',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='O', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='test',
            name='mobile_phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='移动电话'),
        ),
    ]
