# Generated by Django 4.2.10 on 2024-02-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_mobile_admin_mobile_phone_elder_mobile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='mobile_phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='移动电话'),
        ),
    ]
