# Generated by Django 4.2.10 on 2024-02-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_elder_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
