# Generated by Django 4.2.10 on 2024-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_elder_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='imgset_dir',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='remove',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='imgset_dir',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='remove',
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_phone',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='移动电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photo/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='mobile_phone',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='移动电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='resign_date',
            field=models.DateField(blank=True, null=True, verbose_name='离职日期'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='staff_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photo/'),
        ),
        migrations.AlterField(
            model_name='elder',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='座机电话'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_card',
            field=models.CharField(max_length=50, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='座机电话'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id_card',
            field=models.CharField(max_length=50, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='座机电话'),
        ),
    ]
