# Generated by Django 4.2.10 on 2024-03-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='operation_content',
            field=models.TextField(blank=True, null=True, verbose_name='操作信息'),
        ),
        migrations.AlterField(
            model_name='logging',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logging', to='app.test', verbose_name='日志'),
        ),
    ]
