# Generated by Django 4.2.10 on 2024-03-07 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_logging_operation_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='地点')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='主办方')),
                ('participant_limit', models.IntegerField(blank=True, null=True, verbose_name='参与人数限制')),
                ('registration_status', models.BooleanField(default=True, verbose_name='报名状态')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('ongoing', '进行中'), ('finished', '已结束')], default='not_started', max_length=50, verbose_name='活动状态')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系信息')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
                ('image', models.ImageField(blank=True, null=True, upload_to='communityevents/', verbose_name='图片/海报')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类')),
                ('registration_link', models.URLField(blank=True, max_length=1024, null=True, verbose_name='注册/报名链接')),
            ],
            options={
                'verbose_name': '社区活动',
                'verbose_name_plural': '社区活动',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.communityevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.elder')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创键日期')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='过期日期')),
                ('status', models.CharField(choices=[('active', '有效'), ('inactive', '暂时无效'), ('expired', '过期')], default='active', max_length=10, verbose_name='状态')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.test', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '社区公告',
                'verbose_name_plural': '社区公告',
            },
        ),
    ]
