# Generated by Django 4.2.10 on 2024-03-07 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_communityevent_registration_communityannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创键时间'),
            preserve_default=False,
        ),
    ]
