# Generated by Django 4.2.10 on 2024-03-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_communityevent_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityannouncement',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发布方'),
        ),
    ]
