# Generated by Django 4.2.10 on 2024-03-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_communityannouncement_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
