# Generated by Django 4.2.10 on 2024-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_admin_communityevent_activity_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityannouncement',
            name='announcement_photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_photo/'),
        ),
    ]
