# Generated by Django 4.2.10 on 2024-04-02 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_communityannouncement_announcement_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        default="匿名用户", max_length=50, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                        default="O",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="移动电话"
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            ("0", "管理员"),
                            ("1", "工作人员"),
                            ("2", "老年用户"),
                            ("3", "义工用户"),
                            ("4", "其他"),
                        ],
                        default="4",
                        verbose_name="类别",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="自我介绍"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.AddField(
            model_name="elder",
            name="created_by_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="更新人id"),
        ),
        migrations.AddField(
            model_name="elder",
            name="updated_by_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="创建人id"),
        ),
        migrations.AddField(
            model_name="staff",
            name="created_by_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="更新人id"),
        ),
        migrations.AddField(
            model_name="staff",
            name="updated_by_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="创建人id"),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="created_by_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="更新人id"),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="updated_by_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="创建人id"),
        ),
        migrations.AlterField(
            model_name="elder",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="elder",
            name="updated_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="updated_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="updated_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="communityannouncement",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.user",
                verbose_name="发布者",
            ),
        ),
        migrations.AlterField(
            model_name="logging",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Logging",
                to="app.user",
                verbose_name="日志",
            ),
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
