# Generated by Django 4.2.10 on 2024-04-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_user_elder_created_by_id_elder_updated_by_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "男"), ("F", "女"), ("U", "未知")],
                default="U",
                max_length=1,
                verbose_name="性别",
            ),
        ),
    ]
