# Generated by Django 4.2.10 on 2024-04-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_communityannouncement_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elder",
            name="created_by_id",
        ),
        migrations.RemoveField(
            model_name="elder",
            name="updated_by_id",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="created_by_id",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="updated_by_id",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="created_by_id",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="updated_by_id",
        ),
        migrations.AlterField(
            model_name="elder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_created",
                to="app.user",
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="elder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_updated",
                to="app.user",
                verbose_name="更新人",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_created",
                to="app.user",
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_updated",
                to="app.user",
                verbose_name="更新人",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_created",
                to="app.user",
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_updated",
                to="app.user",
                verbose_name="更新人",
            ),
        ),
    ]
