# Generated by Django 4.2.10 on 2024-04-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_remove_elder_created_by_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityannouncement",
            name="introduction",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="简介"
            ),
        ),
    ]
