# Generated by Django 4.2.10 on 2024-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_communityannouncement_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityannouncement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否有效"),
        ),
    ]
