# Generated by Django 4.2.10 on 2024-04-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_communityannouncement_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityannouncement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_created",
                to="app.user",
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="communityannouncement",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="communityannouncement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_updated",
                to="app.user",
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_created",
                to="app.user",
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_updated",
                to="app.user",
                verbose_name="更新人",
            ),
        ),
        migrations.AlterField(
            model_name="communityannouncement",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创键时间"),
        ),
    ]
