# Generated by Django 4.2.10 on 2024-04-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_communityannouncement_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elder",
            name="bind_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elder_data",
                to="app.user",
                verbose_name="绑定用户",
            ),
        ),
        migrations.AddField(
            model_name="logging",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("ADD_RESIDENT", "添加居民"),
                    ("UPDATE_RESIDENT", "更新居民信息"),
                    ("DELETE_RESIDENT", "删除居民"),
                    ("ADD_STAFF", "添加员工"),
                    ("UPDATE_STAFF", "更新员工信息"),
                    ("DELETE_STAFF", "删除员工"),
                    ("ADD_SCHEDULE", "添加排班"),
                    ("UPDATE_SCHEDULE", "更新排班信息"),
                    ("DELETE_SCHEDULE", "删除排班"),
                    ("ADD_MEDICATION", "添加用药记录"),
                    ("UPDATE_MEDICATION", "更新用药记录"),
                    ("DELETE_MEDICATION", "删除用药记录"),
                    ("ADD_ACTIVITY", "添加活动"),
                    ("UPDATE_ACTIVITY", "更新活动信息"),
                    ("DELETE_ACTIVITY", "删除活动"),
                    ("ADD_ANNOUNCEMENT", "发布公告"),
                    ("UPDATE_ANNOUNCEMENT", "更新公告"),
                    ("DELETE_ANNOUNCEMENT", "删除公告"),
                    ("ADD_FEEDBACK", "收集反馈"),
                    ("UPDATE_FEEDBACK", "处理反馈"),
                    ("DELETE_FEEDBACK", "删除反馈"),
                    ("ADD_HEALTH_RECORD", "添加健康记录"),
                    ("UPDATE_HEALTH_RECORD", "更新健康记录"),
                    ("DELETE_HEALTH_RECORD", "删除健康记录"),
                ],
                default=1,
                max_length=20,
                verbose_name="操作类型",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="bind_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_data",
                to="app.user",
                verbose_name="绑定用户",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="bind_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_data",
                to="app.user",
                verbose_name="绑定用户",
            ),
        ),
    ]
