# Generated by Django 4.2.10 on 2024-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_logging_operation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elder",
            name="avatar_photo",
        ),
        migrations.AddField(
            model_name="elder",
            name="elder_photo",
            field=models.ImageField(blank=True, null=True, upload_to="elder_photo/"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_photo",
            field=models.ImageField(blank=True, null=True, upload_to="user_photo/"),
        ),
    ]
