# Generated by Django 4.2.10 on 2024-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_id",
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (0, "情感纠纷"),
                    (1, "意外事件"),
                    (2, "特殊事件"),
                    (3, "服务求助"),
                    (4, "日常协助"),
                ],
                default=0,
                verbose_name="事件类型",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="op_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="记录者id"),
        ),
    ]
