# Generated by Django 4.2.10 on 2024-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_remove_event_event_id_event_event_type_event_op_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否有效"),
        ),
    ]
