# Generated by Django 4.2.10 on 2024-04-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_userip_created_at_alter_userip_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userip",
            name="user_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_user_by",
                to="app.user",
                verbose_name="账户",
            ),
        ),
    ]
