# Generated by Django 4.2.10 on 2024-04-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_elder_bind_user_alter_staff_bind_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logging",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否有效"),
        ),
    ]
