# Generated by Django 4.2.10 on 2024-04-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_user_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="is_save",
            field=models.BooleanField(default=True, verbose_name="是否保存为草稿"),
        ),
    ]
