# Generated by Django 4.2.10 on 2024-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_communityevent_is_save"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="author",
            field=models.CharField(max_length=255, null=True, verbose_name="发布者"),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="introduction",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="简介"
            ),
        ),
        migrations.AlterField(
            model_name="communityannouncement",
            name="author",
            field=models.CharField(max_length=255, null=True, verbose_name="发布者"),
        ),
    ]
