# Generated by Django 4.2.10 on 2024-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_communityevent_author_communityevent_introduction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityevent",
            name="registration_status",
        ),
        migrations.AlterField(
            model_name="communityannouncement",
            name="author",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="发布者"
            ),
        ),
        migrations.AlterField(
            model_name="communityevent",
            name="author",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="发布者"
            ),
        ),
    ]
