# Generated by Django 4.2.10 on 2024-04-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_remove_communityevent_registration_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否有效"),
        ),
    ]
