# Generated by Django 4.2.10 on 2024-04-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_communityevent_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityevent",
            name="cost",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="费用"
            ),
        ),
    ]
