# Generated by Django 4.2.10 on 2024-05-01 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_communityevent_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='服务费用')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预定日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='订单备注')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], null=True, verbose_name='评分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='客户反馈')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='app.elder', verbose_name='老人')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.service', verbose_name='服务')),
            ],
            options={
                'verbose_name': '服务订单',
                'verbose_name_plural': '服务订单',
            },
        ),
    ]
