# Generated by Django 4.2.10 on 2024-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_customer_service_serviceorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='notes',
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='服务费用'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='反馈'),
        ),
    ]
