# Generated by Django 4.2.10 on 2024-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_delete_customer_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
