# Generated by Django 4.2.10 on 2024-05-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_load_service_orders1'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_photo/'),
        ),
    ]
