# Generated by Django 4.2.10 on 2024-05-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_service_service_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_area', models.CharField(max_length=255, verbose_name='分配区域')),
                ('shift_start', models.DateTimeField(verbose_name='班次开始时间')),
                ('shift_end', models.DateTimeField(verbose_name='班次结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.volunteer', verbose_name='义工')),
            ],
            options={
                'verbose_name': '义工排班',
                'verbose_name_plural': '义工排班',
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_area', models.CharField(max_length=255, verbose_name='分配区域')),
                ('shift_start', models.DateTimeField(verbose_name='班次开始时间')),
                ('shift_end', models.DateTimeField(verbose_name='班次结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.staff', verbose_name='工作人员')),
            ],
            options={
                'verbose_name': '工作人员排班',
                'verbose_name_plural': '工作人员排班',
            },
        ),
    ]
