# Generated by Django 4.2.10 on 2024-05-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_service_additional_costs_service_customer_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('daily_care', '日常护理'), ('medical_care', '医疗护理'), ('rehabilitation', '康复护理'), ('leisure', '休闲活动'), ('education', '教育活动')], max_length=20, null=True, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='登录时间'),
        ),
    ]
