# Generated by Django 4.2.10 on 2024-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_service_type_alter_userip_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='服务描述'),
        ),
    ]
