# Generated by Django 4.2.10 on 2024-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('daily_care', '日常护理'), ('medical_care', '医疗护理'), ('rehabilitation', '康复护理'), ('leisure', '休闲活动'), ('education', '教育活动'), ('mental_health', '精神健康')], max_length=20, null=True, verbose_name='服务类型'),
        ),
    ]
