# Generated by Django 4.2.10 on 2024-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_service_created_by_service_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='下单次数'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='服务内容'),
        ),
    ]
