# Generated by Django 4.2.10 on 2024-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_visitnumber_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
