# Generated by Django 4.2.10 on 2024-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_serviceorder_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='elder',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customerName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='客户姓名'),
        ),
    ]
