# Generated by Django 4.2.10 on 2024-05-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_remove_serviceorder_elder_serviceorder_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='customerContact',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='联系方式'),
        ),
    ]
