# Generated by Django 4.2.10 on 2024-05-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_serviceorder_customercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='customerContact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式'),
        ),
    ]
