# Generated by Django 4.2.10 on 2024-05-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_serviceorder_customercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='接受日期'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成日期'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='date_scheduled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预定日期'),
        ),
    ]
