# Generated by Django 4.2.10 on 2024-05-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_serviceorder_aceeptcontact_serviceorder_aceeptname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('accepted', '已接单'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='班次开始时间')),
                ('end_time', models.DateTimeField(verbose_name='班次结束时间')),
                ('area', models.CharField(max_length=100, verbose_name='工作区域')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='app.staff', verbose_name='工作人员')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_shifts', to='app.volunteer', verbose_name='义工')),
            ],
            options={
                'verbose_name': '班次安排',
                'verbose_name_plural': '班次安排',
                'ordering': ['start_time'],
            },
        ),
    ]
