# Generated by Django 4.2.10 on 2024-05-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_serviceorder_status_shiftassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.IntegerField(blank=True, null=True, verbose_name='班次'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期天')], null=True, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工作区域'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='app.staff', verbose_name='工作人员'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_shifts', to='app.volunteer', verbose_name='义工'),
        ),
    ]
