# Generated by Django 4.2.10 on 2024-05-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_shiftassignment_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerassignment',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='StaffAssignment',
        ),
        migrations.DeleteModel(
            name='VolunteerAssignment',
        ),
    ]
