# Generated by Django 4.2.10 on 2024-05-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_shiftassignment_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ShiftAssignment_created', to='app.user', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_ShiftAssignment_updated', to='app.user', verbose_name='更新人'),
        ),
    ]
